# Generated by Django 5.2.1 on 2025-06-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_alter_nota_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nota",
            name="deadline",
            field=models.DateField(),
        ),
    ]
